version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: instaX
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    image: php:7.4-apache
    container_name: my-php
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"

volumes:
  db_data:
